openapi: "3.1.0"
info:
  title: "Youdeyiwu"
  description: "youdeyiwu is an open-source lightweight forum"
  contact:
    name: "Github"
    url: "https://github.com/dafengzhen/youdeyiwu"
  license:
    name: "MIT"
    url: "https://github.com/dafengzhen/youdeyiwu/blob/main/LICENSE"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
    description: "Development server"
paths:
  /configs/jwt/generate-random-secret:
    get:
      summary: "GET configs/jwt/generate-random-secret"
      operationId: "generateRandomSecret"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
  /configs/jwt:
    get:
      summary: "GET configs/jwt"
      operationId: "query"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwtConfigVo"
    put:
      summary: "PUT configs/jwt"
      operationId: "update"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateJwtConfigDto"
        required: true
      responses:
        "204":
          description: "No Content"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Void"
components:
  schemas:
    JwtConfigVo:
      type: "object"
      properties:
        secret:
          type: "string"
    UpdateJwtConfigDto:
      type: "object"
      properties:
        secret:
          type: "string"
    Void:
      type: "object"
      properties: { }