version: "3"
services:
  youdeyiwu:
    labels:
      - maintainer=dafengzhen
      - description=Run youdeyiwu backend application
    container_name: youdeyiwu
    image: "dafengzhen/youdeyiwu:${TAG}"
    environment:
      - TAG
      - PROFILES_ACTIVE
      - DATABASE_NAME
      - DATABASE_ENDPOINT=youdeyiwu:3306
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
    depends_on:
      - youdeyiwu-db
    restart: on-failure
    volumes:
      - logs:/youdeyiwu/logs
    ports:
      - "8080:8080"
    networks:
      - youdeyiwu

  youdeyiwu-web:
    labels:
      - maintainer=dafengzhen
      - description=Build youdeyiwu frontend application
    container_name: youdeyiwu-web
    image: "dafengzhen/youdeyiwu-web:${TAG}"
    environment:
      - TAG
      - URL
      - NAME
      - DESCRIPTION
      - API_SERVER=http://youdeyiwu:8080
      - IS_HTTPS_SITE
      - SERVER_ACTIONS_ALLOWED_ORIGINS=youdeyiwu:8080
      - SHOW_FOOTER
      - IMAGES_REMOTE_PATTERNS_0_PROTOCOL
      - IMAGES_REMOTE_PATTERNS_0_HOSTNAME
      - IMAGES_REMOTE_PATTERNS_0_PORT
      - IMAGES_REMOTE_PATTERNS_0_PATHNAME
    depends_on:
      - youdeyiwu
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - youdeyiwu

  youdeyiwu-db:
    labels:
      - maintainer=dafengzhen
      - description=Build youdeyiwu database application
    container_name: youdeyiwu-db
    image: 'mysql:8.2'
    restart: on-failure
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - youdeyiwu

networks:
  youdeyiwu:
    name: youdeyiwu

volumes:
  db:
    name: youdeyiwu_db
  logs:
    name: youdeyiwu_logs
