name: Publishing Youdeyiwu Backend Application to Docker

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'hosting/**'
      - 'web/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'hosting/**'
      - 'web/**'
  workflow_dispatch:

concurrency:
  group: server
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: dafengzhen/youdeyiwu:dev

  publish:
    needs: build
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: dafengzhen/youdeyiwu:dev
